default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: 123456
  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling

development:
  <<: *default
  database: honda_lpga_development

staging:
  <<: *default
  database: honda_lpga_staging

test:
  <<: *default
  database: honda_lpga_test

production:
  <<: *default
  database: honda_lpga_production
  username: honda_lpga
  password: <%= ENV['honda_lpga_DATABASE_PASSWORD'] %>
